### PR TITLE
misc(package): require node >= 9.4.0

### LINKED ISSUE #2: node: --trace-event-categories is not allowed in NODE_OPTIONS
Hey.

I've encountered this problem using node `9.2.0`, upgrading to `9.4.0` seems to resolve the problem. But what's your idea if adding a hard version dependency in `clinic`'s `package json` to prevent users confusing about this error or at least indicating it in REAME?

Thanks.

### PR DESCRIPTION
**Pull request by pi0**
closes #2.

### CODE REVIEW

**Comment by mcollina** [comment]
This works fine in Node 8.9.4.

**Comment by pi0** [comment]
@mcollina So the only incompatible version is 9.2.0? Sorry if I've missed anything.

**Comment by mcollina** [comment]
Actually no. You need 9.4.0 of the 9 series, but it works with 8.9.4 with a SIGINT handler that close your server.

**Comment by pi0** [comment]
I've also whitelisted `8.9.4` (constraint is `>=9.4.0 8.9.4`)

**Comment by mafintosh** [comment]
@pi0 should prob be >=8.9.4 also

**Comment by pi0** [comment]
OK, i've updated constraint 😆 

image

https://semver.npmjs.com was so useful :)

**Comment by AndreasMadsen** [comment]
Thanks :)

**Pull request merged**
