### PR TITLE
Pass collectDelay arg to Clinic Doctor/Flame

### PR DESCRIPTION
**Pull request by DylanC**
Related to this PR:

Doctor
https://github.com/nearform/node-clinic-doctor/pull/295

Flame
https://github.com/nearform/node-clinic-flame/pull/107
0x
https://github.com/davidmarkclements/0x/pull/222

~BubbleProf - Will be separate from this change
https://github.com/nearform/node-clinic-bubbleprof/pull/346~

The "--collect-delay" arg will be passed in with the arguments and allow the collection of data to be delayed.

### CODE REVIEW

**Comment by DylanC** [comment]
Once this is working for all three I will need to update the parameter from `-t` to `--on-timeout`.

**Comment by DylanC** [comment]
This feature may not work for BubbleProf. Will need to think about a solution or only offer the time delay for Doctor and Flame.

**Comment by jasnell** [comment]
Yeah it's one of the key limitations of bubbleprof I'd say. That that one who may need to collect everything but figure out a way to reasonably filter during the analysis based on timestamp.

**Comment by DylanC** [comment]
@jasnell - Alright, I'll look into this some more and see what could be possible.

**Comment by jasnell** [comment]
For now, I'd say limit the timeout feature to doctor and flame an set the bubbleprof support as a separate task.

**Comment by DylanC** [comment]
@goto-bus-stop - Can I get you to review this and related PR's at some stage today?

**Comment by DylanC** [comment]
@jasnell - Updated with 0x draft PR.

**Comment by goto-bus-stop** [comment]
We should really only merge PRs like this once the other packages have been released, so we don't depend on temporary branches in the package.json

**Comment by DylanC** [comment]
Ah yes! Makes sense!

**Comment by ErisDS** [comment]
Can the revert be reverted? This would be super useful...

**Pull request merged**
